server:
  port: 8080

spring:
  application:
    name: paoding-java
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.qunar.paoding: DEBUG
